### PR TITLE
Lots of improvements

### PR DESCRIPTION
**Pull request by guicho271828**
* faster sync (download all metadata first, use rsync)
* update for ssh-rsa (that is disabled now)
* refactoring

### CODE REVIEW

**Comment by cherti** [comment]
Hey, thanks for all the improvement proposals! :)

Unfortunately, the untabify-commit comes relatively early, making following commits difficult to apply, but I went through the list of improvements and have ported those that I think would make useful additions to the code over to the existing code base by hand instead.

I have noted down a couple of the commits that I still want to take a look at, but given that those will also be hand-ports, I'll proceed with closing this here.

**Comment by guicho271828** [comment]
alright, thanks for checking.

The current scheme that individually download a file is too slow (even if it shares the ssh connection socket) for my reM2 which stores my research paper library of thousands of pdfs. It is a matter of seconds in my port while it takes several minutes in the original.

Perhaps I should make my port separate.

**Comment by cherti** [comment]
when you say download, you are referring to download from or to the remarkable? or do you mean the metadata download? in that case, the stream-json implementation is indeed on my list to look into, but I didn't have the time for that yet.

On that note: what are typical folder-tree-depths in your setup?

**Comment by guicho271828** [comment]
> On that note: what are typical folder-tree-depths in your setup?

Sorry that I did not notice this question.
It is maximum 5-6 levels deep.

**Pull request closed without merging**
